//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPLogAnalyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Average_FWHM {
            get {
                return ((bool)(this["Average_FWHM"]));
            }
            set {
                this["Average_FWHM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ignore_Logs_With_Zero_Targets {
            get {
                return ((bool)(this["Ignore_Logs_With_Zero_Targets"]));
            }
            set {
                this["Ignore_Logs_With_Zero_Targets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Report_Summary {
            get {
                return ((bool)(this["Show_Report_Summary"]));
            }
            set {
                this["Show_Report_Summary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Show_Report_Summary_At_Bottom {
            get {
                return ((bool)(this["Show_Report_Summary_At_Bottom"]));
            }
            set {
                this["Show_Report_Summary_At_Bottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ignore_Targets_With_Zero_Completed_Exposures {
            get {
                return ((bool)(this["Ignore_Targets_With_Zero_Completed_Exposures"]));
            }
            set {
                this["Ignore_Targets_With_Zero_Completed_Exposures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Log_Name {
            get {
                return ((bool)(this["Show_Log_Name"]));
            }
            set {
                this["Show_Log_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Start_Date {
            get {
                return ((bool)(this["Show_Start_Date"]));
            }
            set {
                this["Show_Start_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Show_End_Date {
            get {
                return ((bool)(this["Show_End_Date"]));
            }
            set {
                this["Show_End_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Successful_Plate_Solves {
            get {
                return ((bool)(this["Successful_Plate_Solves"]));
            }
            set {
                this["Successful_Plate_Solves"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Average_Pointing_Error_Slew {
            get {
                return ((bool)(this["Average_Pointing_Error_Slew"]));
            }
            set {
                this["Average_Pointing_Error_Slew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Successful_AutoFocus {
            get {
                return ((bool)(this["Successful_AutoFocus"]));
            }
            set {
                this["Successful_AutoFocus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnSuccessful_AutoFocus {
            get {
                return ((bool)(this["UnSuccessful_AutoFocus"]));
            }
            set {
                this["UnSuccessful_AutoFocus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnSuccessful_Plate_Solves {
            get {
                return ((bool)(this["UnSuccessful_Plate_Solves"]));
            }
            set {
                this["UnSuccessful_Plate_Solves"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Script_Errors {
            get {
                return ((bool)(this["Script_Errors"]));
            }
            set {
                this["Script_Errors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Script_Aborts {
            get {
                return ((bool)(this["Script_Aborts"]));
            }
            set {
                this["Script_Aborts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Auto_Focus_Time {
            get {
                return ((bool)(this["Average_Auto_Focus_Time"]));
            }
            set {
                this["Average_Auto_Focus_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.rarcher.net/acpLogAnalyzerHelp.html")]
        public string Help_Text_Url {
            get {
                return ((string)(this["Help_Text_Url"]));
            }
            set {
                this["Help_Text_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Average_Pointing_Error_Center {
            get {
                return ((bool)(this["Average_Pointing_Error_Center"]));
            }
            set {
                this["Average_Pointing_Error_Center"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Average_FWHM_Overall {
            get {
                return ((bool)(this["Average_FWHM_Overall"]));
            }
            set {
                this["Average_FWHM_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Pointing_Error_Slew_Overall {
            get {
                return ((bool)(this["Average_Pointing_Error_Slew_Overall"]));
            }
            set {
                this["Average_Pointing_Error_Slew_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Pointing_Error_Center_Overall {
            get {
                return ((bool)(this["Average_Pointing_Error_Center_Overall"]));
            }
            set {
                this["Average_Pointing_Error_Center_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Auto_Focus_Time_Overall {
            get {
                return ((bool)(this["Average_Auto_Focus_Time_Overall"]));
            }
            set {
                this["Average_Auto_Focus_Time_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Successful_AutoFocus_Overall {
            get {
                return ((bool)(this["Successful_AutoFocus_Overall"]));
            }
            set {
                this["Successful_AutoFocus_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnSuccessful_AutoFocus_Overall {
            get {
                return ((bool)(this["UnSuccessful_AutoFocus_Overall"]));
            }
            set {
                this["UnSuccessful_AutoFocus_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Successful_Plate_Solves_Overall {
            get {
                return ((bool)(this["Successful_Plate_Solves_Overall"]));
            }
            set {
                this["Successful_Plate_Solves_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnSuccessful_Plate_Solves_Overall {
            get {
                return ((bool)(this["UnSuccessful_Plate_Solves_Overall"]));
            }
            set {
                this["UnSuccessful_Plate_Solves_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Total_Logs_Parsed {
            get {
                return ((bool)(this["Show_Total_Logs_Parsed"]));
            }
            set {
                this["Show_Total_Logs_Parsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Total_Targets {
            get {
                return ((bool)(this["Show_Total_Targets"]));
            }
            set {
                this["Show_Total_Targets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Total_Image_Count {
            get {
                return ((bool)(this["Show_Total_Image_Count"]));
            }
            set {
                this["Show_Total_Image_Count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Target_Details {
            get {
                return ((bool)(this["Show_Target_Details"]));
            }
            set {
                this["Show_Target_Details"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Target_Name {
            get {
                return ((bool)(this["Show_Target_Name"]));
            }
            set {
                this["Show_Target_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Completed_Exposure_Details {
            get {
                return ((bool)(this["Show_Completed_Exposure_Details"]));
            }
            set {
                this["Show_Completed_Exposure_Details"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Total_Imaging_Time_Per_Target {
            get {
                return ((bool)(this["Show_Total_Imaging_Time_Per_Target"]));
            }
            set {
                this["Show_Total_Imaging_Time_Per_Target"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Is_First_Run {
            get {
                return ((bool)(this["Is_First_Run"]));
            }
            set {
                this["Is_First_Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sort_By_Date_Asc {
            get {
                return ((bool)(this["Sort_By_Date_Asc"]));
            }
            set {
                this["Sort_By_Date_Asc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sort_By_Date {
            get {
                return ((bool)(this["Sort_By_Date"]));
            }
            set {
                this["Sort_By_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Guider_StartUp_Time {
            get {
                return ((bool)(this["Average_Guider_StartUp_Time"]));
            }
            set {
                this["Average_Guider_StartUp_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Guider_StartUp_Time_Overall {
            get {
                return ((bool)(this["Average_Guider_StartUp_Time_Overall"]));
            }
            set {
                this["Average_Guider_StartUp_Time_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Guider_Settle_Time {
            get {
                return ((bool)(this["Average_Guider_Settle_Time"]));
            }
            set {
                this["Average_Guider_Settle_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Guider_Settle_Time_Overall {
            get {
                return ((bool)(this["Average_Guider_Settle_Time_Overall"]));
            }
            set {
                this["Average_Guider_Settle_Time_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Filter_Change_Time {
            get {
                return ((bool)(this["Average_Filter_Change_Time"]));
            }
            set {
                this["Average_Filter_Change_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Filter_Change_Time_Overall {
            get {
                return ((bool)(this["Average_Filter_Change_Time_Overall"]));
            }
            set {
                this["Average_Filter_Change_Time_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Plate_Solve_Time {
            get {
                return ((bool)(this["Average_Plate_Solve_Time"]));
            }
            set {
                this["Average_Plate_Solve_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Plate_Solve_Time_Overall {
            get {
                return ((bool)(this["Average_Plate_Solve_Time_Overall"]));
            }
            set {
                this["Average_Plate_Solve_Time_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Slew_Time_Targets {
            get {
                return ((bool)(this["Average_Slew_Time_Targets"]));
            }
            set {
                this["Average_Slew_Time_Targets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Average_Slew_Time_Targets_Overall {
            get {
                return ((bool)(this["Average_Slew_Time_Targets_Overall"]));
            }
            set {
                this["Average_Slew_Time_Targets_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Runtime_Breakdown {
            get {
                return ((bool)(this["Runtime_Breakdown"]));
            }
            set {
                this["Runtime_Breakdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Runtime_Breakdown_Overall {
            get {
                return ((bool)(this["Runtime_Breakdown_Overall"]));
            }
            set {
                this["Runtime_Breakdown_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Total_Guiding_Failures {
            get {
                return ((bool)(this["Show_Total_Guiding_Failures"]));
            }
            set {
                this["Show_Total_Guiding_Failures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Total_Guiding_Failures_Overall {
            get {
                return ((bool)(this["Show_Total_Guiding_Failures_Overall"]));
            }
            set {
                this["Show_Total_Guiding_Failures_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.rarcher.net/acpLogAnalyzerHelp.html?panel=config")]
        public string Help_Text_Config_Url {
            get {
                return ((string)(this["Help_Text_Config_Url"]));
            }
            set {
                this["Help_Text_Config_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Total_Guiding_Failures_Breakdown {
            get {
                return ((bool)(this["Show_Total_Guiding_Failures_Breakdown"]));
            }
            set {
                this["Show_Total_Guiding_Failures_Breakdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_Total_Guiding_Failures_Overall_Breakdown {
            get {
                return ((bool)(this["Show_Total_Guiding_Failures_Overall_Breakdown"]));
            }
            set {
                this["Show_Total_Guiding_Failures_Overall_Breakdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.rarcher.net/_files/ACPLogAnalyzer.txt")]
        public string Version_Check_Url {
            get {
                return ((string)(this["Version_Check_Url"]));
            }
            set {
                this["Version_Check_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Always_Check_For_Updates {
            get {
                return ((bool)(this["Always_Check_For_Updates"]));
            }
            set {
                this["Always_Check_For_Updates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Most_Recent_Search_Dir {
            get {
                return ((string)(this["Most_Recent_Search_Dir"]));
            }
            set {
                this["Most_Recent_Search_Dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string Plot_Font_Name {
            get {
                return ((string)(this["Plot_Font_Name"]));
            }
            set {
                this["Plot_Font_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string Plot_Font_Size {
            get {
                return ((string)(this["Plot_Font_Size"]));
            }
            set {
                this["Plot_Font_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Plot_Always_Show_Avg {
            get {
                return ((bool)(this["Plot_Always_Show_Avg"]));
            }
            set {
                this["Plot_Always_Show_Avg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string Plot_Font_Weight {
            get {
                return ((string)(this["Plot_Font_Weight"]));
            }
            set {
                this["Plot_Font_Weight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string Plot_Font_Style {
            get {
                return ((string)(this["Plot_Font_Style"]));
            }
            set {
                this["Plot_Font_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Plot_FG_Color {
            get {
                return ((global::System.Drawing.Color)(this["Plot_FG_Color"]));
            }
            set {
                this["Plot_FG_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Plot_FG_Color_Title {
            get {
                return ((global::System.Drawing.Color)(this["Plot_FG_Color_Title"]));
            }
            set {
                this["Plot_FG_Color_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string Plot_Font_Name_Title {
            get {
                return ((string)(this["Plot_Font_Name_Title"]));
            }
            set {
                this["Plot_Font_Name_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public string Plot_Font_Size_Title {
            get {
                return ((string)(this["Plot_Font_Size_Title"]));
            }
            set {
                this["Plot_Font_Size_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string Plot_Font_Style_Title {
            get {
                return ((string)(this["Plot_Font_Style_Title"]));
            }
            set {
                this["Plot_Font_Style_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string Plot_Font_Weight_Title {
            get {
                return ((string)(this["Plot_Font_Weight_Title"]));
            }
            set {
                this["Plot_Font_Weight_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Plot_BG_Graph {
            get {
                return ((global::System.Drawing.Color)(this["Plot_BG_Graph"]));
            }
            set {
                this["Plot_BG_Graph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Plot_BG_Key {
            get {
                return ((global::System.Drawing.Color)(this["Plot_BG_Key"]));
            }
            set {
                this["Plot_BG_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Plot_BG_Key_Transparent {
            get {
                return ((bool)(this["Plot_BG_Key_Transparent"]));
            }
            set {
                this["Plot_BG_Key_Transparent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public double Plot_Main_Thickness {
            get {
                return ((double)(this["Plot_Main_Thickness"]));
            }
            set {
                this["Plot_Main_Thickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double Plot_Secondary_Thickness {
            get {
                return ((double)(this["Plot_Secondary_Thickness"]));
            }
            set {
                this["Plot_Secondary_Thickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CornflowerBlue")]
        public global::System.Drawing.Color Plot_Main_Line_Color {
            get {
                return ((global::System.Drawing.Color)(this["Plot_Main_Line_Color"]));
            }
            set {
                this["Plot_Main_Line_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IndianRed")]
        public global::System.Drawing.Color Plot_Secondary_Line_Color {
            get {
                return ((global::System.Drawing.Color)(this["Plot_Secondary_Line_Color"]));
            }
            set {
                this["Plot_Secondary_Line_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Plot_Main_Show_Data_Points {
            get {
                return ((bool)(this["Plot_Main_Show_Data_Points"]));
            }
            set {
                this["Plot_Main_Show_Data_Points"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Plot_Secondary_Show_Data_Points {
            get {
                return ((bool)(this["Plot_Secondary_Show_Data_Points"]));
            }
            set {
                this["Plot_Secondary_Show_Data_Points"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.rarcher.net/_files/logAnalyzerRelNotes.html")]
        public string Release_Notes_Url {
            get {
                return ((string)(this["Release_Notes_Url"]));
            }
            set {
                this["Release_Notes_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Average_HFD {
            get {
                return ((bool)(this["Average_HFD"]));
            }
            set {
                this["Average_HFD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Average_HFD_Overall {
            get {
                return ((bool)(this["Average_HFD_Overall"]));
            }
            set {
                this["Average_HFD_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SeaGreen")]
        public global::System.Drawing.Color Plot_Tertiary_Line_Color {
            get {
                return ((global::System.Drawing.Color)(this["Plot_Tertiary_Line_Color"]));
            }
            set {
                this["Plot_Tertiary_Line_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Plot_Tertiary_Show_Data_Points {
            get {
                return ((bool)(this["Plot_Tertiary_Show_Data_Points"]));
            }
            set {
                this["Plot_Tertiary_Show_Data_Points"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double Plot_Tertiary_Thickness {
            get {
                return ((double)(this["Plot_Tertiary_Thickness"]));
            }
            set {
                this["Plot_Tertiary_Thickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.rarcher.net/_files/ACPLogAnalyzerSetup.msi")]
        public string Update_Download_Url {
            get {
                return ((string)(this["Update_Download_Url"]));
            }
            set {
                this["Update_Download_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_AllSky_Success_Count {
            get {
                return ((bool)(this["Show_AllSky_Success_Count"]));
            }
            set {
                this["Show_AllSky_Success_Count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_AllSky_Fail_Count {
            get {
                return ((bool)(this["Show_AllSky_Fail_Count"]));
            }
            set {
                this["Show_AllSky_Fail_Count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_AllSky_Time {
            get {
                return ((bool)(this["Show_AllSky_Time"]));
            }
            set {
                this["Show_AllSky_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_AllSky_Overall_Time {
            get {
                return ((bool)(this["Show_AllSky_Overall_Time"]));
            }
            set {
                this["Show_AllSky_Overall_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_AllSky_Success_Count_Overall {
            get {
                return ((bool)(this["Show_AllSky_Success_Count_Overall"]));
            }
            set {
                this["Show_AllSky_Success_Count_Overall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show_AllSky_Fail_Count_Overall {
            get {
                return ((bool)(this["Show_AllSky_Fail_Count_Overall"]));
            }
            set {
                this["Show_AllSky_Fail_Count_Overall"] = value;
            }
        }
    }
}
